sudo: required
notifications:
  slack: srboeingdotnet:ne7IgGiOz5eVARMY1IwEXGZg
language: node_js
node_js:
  - node
os:
  - linux
install:
  - npm install
script:
  - npm run lint
  - npm run test
notifications:
  email:
    on_success: always
    on_failure: always
